services:
  postgres:
    image: postgres:15.1
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: front
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app

networks:
  app:
    external: true